// SAMPLE DATA — fictional listings for demo purposes. Replace with real inventory
// (or use "Add listing" / "Import CSV" in the app).
// monthly = rate for a 30+ night stay, USD. utilities: true if included in rate.
window.SAMPLE_LISTINGS = [
  { id: "s1", name: "Harbor View Residences", provider: "Direct", city: "Boston", neighborhood: "Seaport", beds: 1, baths: 1, sqft: 720, sleeps: 2, monthly: 4100, minNights: 30, utilities: true, amenities: ["Furnished","Gym","Washer/Dryer","Parking","Wi-Fi"], petFriendly: false, notes: "Walk to South Station. Weekly housekeeping available." },
  { id: "s2", name: "Back Bay Executive Suites", provider: "Marriott Executive Apartments", city: "Boston", neighborhood: "Back Bay", beds: 2, baths: 2, sqft: 1050, sleeps: 4, monthly: 6200, minNights: 30, utilities: true, amenities: ["Furnished","Gym","Washer/Dryer","Concierge","Wi-Fi"], petFriendly: true, notes: "Pet fee $250 one-time." },
  { id: "s3", name: "Kendall Square Studio", provider: "Furnished Finder", city: "Boston", neighborhood: "Cambridge", beds: 0, baths: 1, sqft: 480, sleeps: 2, monthly: 3100, minNights: 90, utilities: false, amenities: ["Furnished","Wi-Fi","Washer/Dryer"], petFriendly: false, notes: "Near MIT / biotech campuses." },
  { id: "s4", name: "Midtown Loft 22", provider: "Oakwood", city: "New York", neighborhood: "Midtown", beds: 1, baths: 1, sqft: 650, sleeps: 2, monthly: 5900, minNights: 30, utilities: true, amenities: ["Furnished","Gym","Concierge","Wi-Fi","Doorman"], petFriendly: false, notes: "Corporate billing available." },
  { id: "s5", name: "Brooklyn Heights 2BR", provider: "Direct", city: "New York", neighborhood: "Brooklyn Heights", beds: 2, baths: 1, sqft: 900, sleeps: 4, monthly: 5400, minNights: 60, utilities: false, amenities: ["Furnished","Washer/Dryer","Wi-Fi"], petFriendly: true, notes: "Quiet block, 2 subway lines." },
  { id: "s6", name: "Financial District Studio", provider: "Sentral", city: "New York", neighborhood: "FiDi", beds: 0, baths: 1, sqft: 420, sleeps: 2, monthly: 4300, minNights: 30, utilities: true, amenities: ["Furnished","Gym","Doorman","Wi-Fi"], petFriendly: false, notes: "" },
  { id: "s7", name: "Domain Corporate Flats", provider: "Landing", city: "Austin", neighborhood: "The Domain", beds: 1, baths: 1, sqft: 700, sleeps: 2, monthly: 2650, minNights: 30, utilities: true, amenities: ["Furnished","Gym","Pool","Washer/Dryer","Parking","Wi-Fi"], petFriendly: true, notes: "Flexible month-to-month after first term." },
  { id: "s8", name: "Downtown Austin 2BR", provider: "Direct", city: "Austin", neighborhood: "Downtown", beds: 2, baths: 2, sqft: 1100, sleeps: 4, monthly: 3900, minNights: 30, utilities: false, amenities: ["Furnished","Pool","Gym","Parking","Wi-Fi"], petFriendly: true, notes: "Walkable to Congress Ave." },
  { id: "s9", name: "South Congress Casita", provider: "Furnished Finder", city: "Austin", neighborhood: "SoCo", beds: 1, baths: 1, sqft: 560, sleeps: 2, monthly: 2200, minNights: 30, utilities: true, amenities: ["Furnished","Washer/Dryer","Wi-Fi","Parking"], petFriendly: true, notes: "Private entrance." },
  { id: "s10", name: "SoMa Business Lofts", provider: "Oakwood", city: "San Francisco", neighborhood: "SoMa", beds: 1, baths: 1, sqft: 680, sleeps: 2, monthly: 5200, minNights: 30, utilities: true, amenities: ["Furnished","Gym","Concierge","Wi-Fi","Parking"], petFriendly: false, notes: "Near Caltrain & Salesforce Park." },
  { id: "s11", name: "Mission Bay 2BR", provider: "Landing", city: "San Francisco", neighborhood: "Mission Bay", beds: 2, baths: 2, sqft: 1000, sleeps: 4, monthly: 6800, minNights: 30, utilities: false, amenities: ["Furnished","Gym","Washer/Dryer","Parking","Wi-Fi"], petFriendly: true, notes: "Close to UCSF campus." },
  { id: "s12", name: "Uptown Dallas Suites", provider: "Marriott Executive Apartments", city: "Dallas", neighborhood: "Uptown", beds: 1, baths: 1, sqft: 750, sleeps: 2, monthly: 2400, minNights: 30, utilities: true, amenities: ["Furnished","Gym","Pool","Washer/Dryer","Wi-Fi"], petFriendly: true, notes: "" },
  { id: "s13", name: "Legacy West 3BR", provider: "Direct", city: "Dallas", neighborhood: "Plano", beds: 3, baths: 2, sqft: 1500, sleeps: 6, monthly: 4300, minNights: 60, utilities: false, amenities: ["Furnished","Washer/Dryer","Parking","Pool","Wi-Fi"], petFriendly: true, notes: "Good for relocating families / project teams." },
  { id: "s14", name: "Midtown Atlanta Studio", provider: "Sentral", city: "Atlanta", neighborhood: "Midtown", beds: 0, baths: 1, sqft: 450, sleeps: 2, monthly: 2100, minNights: 30, utilities: true, amenities: ["Furnished","Gym","Wi-Fi","Doorman"], petFriendly: false, notes: "MARTA adjacent." },
  { id: "s15", name: "Buckhead Executive 2BR", provider: "Oakwood", city: "Atlanta", neighborhood: "Buckhead", beds: 2, baths: 2, sqft: 1150, sleeps: 4, monthly: 3800, minNights: 30, utilities: true, amenities: ["Furnished","Gym","Pool","Washer/Dryer","Parking","Concierge","Wi-Fi"], petFriendly: true, notes: "" },
  { id: "s16", name: "Capitol Hill Flat", provider: "Furnished Finder", city: "Washington DC", neighborhood: "Capitol Hill", beds: 1, baths: 1, sqft: 620, sleeps: 2, monthly: 3500, minNights: 30, utilities: false, amenities: ["Furnished","Washer/Dryer","Wi-Fi"], petFriendly: false, notes: "Short walk to Union Station." }
];
